/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          red: '#bd0014',
          yellow: '#ffce07',
          green: '#00B201',
          black: '#000000',
          white: '#ffffff',
        },
        primary: '#bd0014',
        'on-primary': '#ffffff',
        'primary-container': '#ffdada',
        'on-primary-container': '#410010',
        background: '#fff8f7',
        'on-background': '#291715',
        surface: '#fff8f7',
        'surface-bright': '#fff8f7',
        'surface-variant': '#fcdbd7',
        'on-surface': '#291715',
        'on-surface-variant': '#5d3f3c',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e2e2',
        'on-secondary-container': '#646464',
        tertiary: '#735c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffe087',
        'on-tertiary-container': '#4e3e00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#402b29',
        'inverse-on-surface': '#ffedea',
        'inverse-primary': '#ffb4ac',
        'outline': '#926f6b',
        'outline-variant': '#e7bdb8',
        'surface-dim': '#f4d3cf',
        'surface-tint': '#c00015',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0ee',
        'surface-container': '#ffe9e6',
        'surface-container-high': '#ffe2de',
        'surface-container-highest': '#fcdbd7',
      },
      fontFamily: {
        'display': ['Epilogue', 'sans-serif'],
        'body': ['Montserrat', 'sans-serif'],
        'label': ['JetBrains Mono', 'monospace'],
        heading: ['Epilogue', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-sm': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '4px',
        DEFAULT: '8px',
        'lg': '12px',
        'xl': '16px',
        'full': '9999px',
      },
      boxShadow: {
        'card': '4px 4px 0 #291715',
        'card-hover': '2px 2px 0 #291715',
        'card-sm': '3px 3px 0 #291715',
      },
      spacing: {
        'gutter': '1.5rem',
        'margin': '2rem',
      },
    },
  },
  plugins: [],
};