/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#e42327',
        secondary: '#000000',
        tertiary: '#ffce07',
        success: '#00B201',
        'on-primary': '#ffffff',
        background: '#fff8f7',
        surface: '#fff8f7',
        'surface-container': '#ffe9e6',
        'surface-container-low': '#fff0ee',
        'surface-container-highest': '#fcdbd7',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#000000',
        'on-surface-variant': '#5d3f3c',
        outline: '#926f6b',
        'outline-variant': '#e7bdb8',
        'border-muted': '#E5E7EB',
        'primary-container': '#e42327',
        'on-primary-container': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '80px',
        'container-max': '1280px',
        base: '8px',
        'margin-mobile': '16px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Epilogue', 'sans-serif'],
        'display-lg': ['Epilogue', 'sans-serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'label-sm': ['Montserrat', 'sans-serif'],
        heading: ['Epilogue', 'sans-serif'],
        body: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        DEFAULT: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
};